-- 1. Create Profiles Table (Public Profile Data)
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  email text not null,
  full_name text,
  phone text,
  role text not null default 'masyarakat' check (role in ('masyarakat', 'petugas', 'admin')),
  status text not null default 'active' check (status in ('active', 'pending', 'rejected', 'deleted')),
  created_at timestamptz not null default now(),
  primary key (id)
);

-- 2. Enable RLS on Profiles
alter table public.profiles enable row level security;

-- 3. Create RLS Policies for Profiles
-- Public can read profiles (or just authenticated users, depending on need. For now allow auth)
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

-- Users can update their own profile
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 4. Create Trigger to automatically create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, phone, role, status)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'phone',
    coalesce(new.raw_user_meta_data ->> 'role', 'masyarakat'),
    'active'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 5. Create Kategori Pengaduan Table
create table public.kategori_pengaduan (
  id bigint generated by default as identity primary key,
  nama text not null,
  created_at timestamptz default now()
);

alter table public.kategori_pengaduan enable row level security;

create policy "Kategori is viewable by everyone"
  on kategori_pengaduan for select using (true);

-- Seed Data for Kategori
insert into public.kategori_pengaduan (nama) values
  ('Infrastruktur (Jalan/Jembatan)'),
  ('Kebersihan & Sampah'),
  ('Keamanan & Ketertiban'),
  ('Pelayanan Publik'),
  ('Kesehatan'),
  ('Bencana Alam'),
  ('Lainnya');

-- 6. Create Pengaduan Table
create table public.pengaduan (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  judul text not null,
  deskripsi text not null,
  kategori_id bigint references public.kategori_pengaduan(id),
  foto_url text,
  latitude float,
  longitude float,
  alamat text,
  status text default 'pending' check (status in ('pending', 'verified', 'assigned', 'in_progress', 'completed', 'rejected')),
  petugas_id uuid references public.profiles(id),
  created_at timestamptz default now()
);

alter table public.pengaduan enable row level security;

-- Policies for Pengaduan
create policy "Pengaduan viewable by everyone"
  on pengaduan for select using (true);

create policy "Users can insert their own pengaduan"
  on pengaduan for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own pengaduan"
  on pengaduan for update
  using ( auth.uid() = user_id );

-- 7. Storage Bucket Setup (Cannot be fully scripted via SQL in all Supabase versions, but policy can)
-- insert into storage.buckets (id, name, public) values ('pengaduan-photos', 'pengaduan-photos', true);
-- create policy "Images are publicly accessible." on storage.objects for select using ( bucket_id = 'pengaduan-photos' );
-- create policy "Anyone can upload an image." on storage.objects for insert with check ( bucket_id = 'pengaduan-photos' );

-- 8. RPC Function for Safe Account Deletion (Hard Delete)
create or replace function delete_own_account()
returns void
language plpgsql
security definer
as $$
begin
  delete from auth.users where id = auth.uid();
end;
$$;
